language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install urllib==1.22
  - "python setup.py install"
  - pip install mock
  - pip install pytest
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
# command to run tests
script: py.test
env: BOTO_CONFIG=/tmp/nowhere
